# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loader', '0002_auto_20160628_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField(default=60)),
                ('running', models.BooleanField(default=True)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loader.Campaign')),
                ('data_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loader.BatchData')),
            ],
        ),
    ]
