# Generated by Django 2.0.4 on 2018-04-18 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_file', models.FileField(blank=True, null=True, upload_to='logs/')),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField(default=60)),
                ('running', models.BooleanField(default=True)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loader.Campaign')),
                ('data_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loader.BatchData')),
            ],
        ),
    ]
