# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-27 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='log_file',
            field=models.FileField(blank=True, null=True, upload_to='logs/'),
        ),
    ]
