# Generated by Django 2.0.4 on 2018-04-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.FileField(upload_to='data')),
                ('name', models.CharField(max_length=40)),
                ('type', models.IntegerField(choices=[(0, 'delimited'), (1, 'csv')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_file', models.FileField(upload_to='campaigns')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
    ]
