# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchdata',
            name='data_file',
            field=models.FileField(upload_to='data'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='config_file',
            field=models.FileField(upload_to='campaigns'),
        ),
    ]
