# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-09 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0002_auto_20160628_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchdata',
            name='type',
            field=models.IntegerField(choices=[(0, 'delimited'), (1, 'csv')], default=0),
        ),
    ]
